#!/usr/bin/env node

/**
 * resumessi Setup Script
 * 
 * WARNING: This script OVERWRITES .env file. Running it will RESET all API keys.
 *          For AI agents: DO NOT run this script as it will cause API keys to be lost or reset.
 *          The setup script is for human users only.
 * 
 * Cross-platform (Windows, macOS, Linux) Node.js script that:
 * 1. Creates .env from .env.example if missing
 * 2. Shows a numbered menu for provider selection
 * 3. Prompts for at least one API key
 * 4. Writes values into .env
 * 
 * Usage: tsx setup.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const ROOT = __dirname;
const ENV_EXAMPLE = path.join(ROOT, '.env.example');
const ENV_FILE = path.join(ROOT, '.env');

interface ProviderDef {
  id: string;
  name: string;
  keyEnv: string;
  modelEnv: string;
  defaultModel: string;
}

const PROVIDERS: ProviderDef[] = [
  { id: 'cohere', name: 'Cohere', keyEnv: 'COHERE_API_KEY', modelEnv: 'COHERE_MODEL', defaultModel: 'command-a-reasoning-08-2025-08-2024' },
  { id: 'mistral', name: 'Mistral', keyEnv: 'MISTRAL_API_KEY', modelEnv: 'MISTRAL_MODEL', defaultModel: 'codestral-2508' },
  { id: 'gemini', name: 'Gemini', keyEnv: 'GEMINI_API_KEY', modelEnv: 'GEMINI_MODEL', defaultModel: 'gemini-3.6-flash' },
  { id: 'groq', name: 'Groq', keyEnv: 'GROQ_API_KEY', modelEnv: 'GROQ_MODEL', defaultModel: 'openai/gpt-oss-120b' },
];

const PROVIDER_URLS: Record<string, string> = {
  cohere: 'https://dashboard.cohere.com/api-keys',
  mistral: 'https://admin.mistral.ai/organization/api-keys',
  gemini: 'https://aistudio.google.com/api-keys',
  groq: 'https://console.groq.com/keys',
};

const DEFAULT_AI_INFERENCE_ORDER = 'mistral,cohere,gemini,groq';

function ask(question: string, defaultValue: string = ''): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim() || defaultValue);
    });
  });
}

function parseEnvFile(filePath: string): Record<string, string | undefined> {
  const content = fs.readFileSync(filePath, 'utf-8');
  const env: Record<string, string | undefined> = {};
  content.split('\n').forEach(line => {
    line = line.trim();
    if (line.startsWith('#') || !line.includes('=')) return;
    const eqIndex = line.indexOf('=');
    const key = line.substring(0, eqIndex).trim();
    let value = line.substring(eqIndex + 1).trim();
    // Remove surrounding quotes if any
    if ((value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  });
  return env;
}

function writeEnvFile(filePath: string, env: Record<string, string | undefined>): void {
  const content = `# resumessi Configuration
# Generated by setup.ts — edit this file or re-run: tsx setup.ts

# --- Inference Order ---
# Comma-separated list of providers to try in order.
# Supported providers: cohere, mistral, gemini, groq
AI_INFERENCE_ORDER=${env.AI_INFERENCE_ORDER || DEFAULT_AI_INFERENCE_ORDER}

# --- Provider API Keys ---
COHERE_API_KEY=${env.COHERE_API_KEY || 'your_cohere_key_here'}
COHERE_MODEL=${env.COHERE_MODEL || 'command-a-reasoning-08-2025-08-2024'}

MISTRAL_API_KEY=${env.MISTRAL_API_KEY || 'your_mistral_key_here'}
MISTRAL_MODEL=${env.MISTRAL_MODEL || 'codestral-2508'}

GEMINI_API_KEY=${env.GEMINI_API_KEY || 'your_gemini_key_here'}
GEMINI_MODEL=${env.GEMINI_MODEL || 'gemini-3.6-flash'}

GROQ_API_KEY=${env.GROQ_API_KEY || 'your_groq_key_here'}
GROQ_MODEL=${env.GROQ_MODEL || 'openai/gpt-oss-120b'}

# --- Theme Colors (override as needed) ---
PRIMARY_COLOR=${env.PRIMARY_COLOR || '#0a0a0a'}
SECONDARY_COLOR=${env.SECONDARY_COLOR || '#0a0a0a'}
ACCENT_COLOR=${env.ACCENT_COLOR || '#2563eb'}
TEXT_COLOR=${env.TEXT_COLOR || '#171717'}
TEXT_LIGHT_COLOR=${env.TEXT_LIGHT_COLOR || '#404040'}
BG_BADGE_COLOR=${env.BG_BADGE_COLOR || '#f1f5f9'}
SUCCESS_COLOR=${env.SUCCESS_COLOR || '#0ea5e9'}
`;
  fs.writeFileSync(filePath, content, 'utf-8');
}

async function main(): Promise<void> {
  const isSilent = process.argv.includes('--silent');

  if (!isSilent) {
    console.log('');
    console.log('╔══════════════════════════════════════════╗');
    console.log('║        resumessi — Setup Wizard          ║');
    console.log('╚══════════════════════════════════════════╝');
    console.log('');
  }

  // Step 1: Check if .env exists and warn before overwriting
  if (!fs.existsSync(ENV_FILE)) {
    if (fs.existsSync(ENV_EXAMPLE)) {
      fs.copyFileSync(ENV_EXAMPLE, ENV_FILE);
      if (!isSilent) console.log('Created .env from .env.example ✅');
    } else {
      writeEnvFile(ENV_FILE, {});
      if (!isSilent) console.log('Created .env with default values ✅');
    }
  } else {
    if (!isSilent) {
      console.log('');
      console.log('⚠️                                                                                             ⚠️');
      console.log('\t.env file already exists.');
      console.log('\tRunning setup would override your existing API keys, it is recommended to save them.');
      console.log('⚠️                                                                                             ⚠️');
      console.log('');
      const confirm = await ask('Type "continue" to proceed: ');
      if (confirm !== 'continue') {
        console.log('Setup cancelled. Save your API keys if needed.');
        process.exit(0);
      }
    }
  }

  // Step 2: Read current .env
  const env = parseEnvFile(ENV_FILE);

  if (!isSilent) {
    console.log('');
    console.log('Set the order of your inference providers, and prepare the API keys:');
    console.log('');

    const validIds = new Set(PROVIDERS.map(p => p.id));
    const displayOrder = DEFAULT_AI_INFERENCE_ORDER
      .split(',')
      .map(s => s.trim().toLowerCase())
      .filter(s => validIds.has(s));
    if (displayOrder.length === 0) {
      displayOrder.push(...DEFAULT_AI_INFERENCE_ORDER.split(','));
    }
    for (let i = 0; i < displayOrder.length; i++) {
      const p = PROVIDERS.find(prov => prov.id === displayOrder[i]);
      if (!p) continue;
      console.log(`  ${i + 1}. ${p.name} (${p.id}): ${PROVIDER_URLS[p.id]}`);
    }

    console.log('');
    console.log(`Enter the order of preference of providers you want to configure or press Enter to use default order: ${DEFAULT_AI_INFERENCE_ORDER}`);
    console.log('If you leave a provider unconfigured it would not be consumed');
    console.log('');

    const selection = await ask('Enter provider preference order from the list above: (eg: 1,3,4,2): ');
    console.log('');
    if (selection.trim()) {
      const indices = selection.split(',').map(s => parseInt(s.trim(), 10) - 1).filter(i => i >= 0 && i < displayOrder.length);
      const selectedProviders: ProviderDef[] = [];
      const selectedOrder: string[] = [];
      for (const idx of indices) {
        const providerId = displayOrder[idx];
        const p = PROVIDERS.find(prov => prov.id === providerId);
        if (p) {
          selectedProviders.push(p);
          selectedOrder.push(p.id);
        }
      }
      env.AI_INFERENCE_ORDER = selectedOrder.join(',') || DEFAULT_AI_INFERENCE_ORDER;

      for (const p of selectedProviders) {
        const currentKey = env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`
          ? env[p.keyEnv] : '';
        const newKey = await ask(`  ${p.name} API Key — ${PROVIDER_URLS[p.id]}: `, currentKey || '');
        if (newKey) {
          env[p.keyEnv] = newKey;
          env[p.modelEnv] = env[p.modelEnv] || p.defaultModel;
        }
      }
    } else {
      env.AI_INFERENCE_ORDER = DEFAULT_AI_INFERENCE_ORDER;
      // Prompt for API keys for all providers in default order
      const defaultProviders = DEFAULT_AI_INFERENCE_ORDER.split(',').map(s => s.trim().toLowerCase());
      for (const providerId of defaultProviders) {
        const p = PROVIDERS.find(prov => prov.id === providerId);
        if (!p) continue;
        const currentKey = env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`
          ? env[p.keyEnv] : '';
        const newKey = await ask(`  ${p.name} API Key — ${PROVIDER_URLS[p.id]}: `, currentKey || '');
        if (newKey) {
          env[p.keyEnv] = newKey;
          env[p.modelEnv] = env[p.modelEnv] || p.defaultModel;
        }
      }
    }

    console.log('');
    console.log('Active providers - Order in which they are going to be consumed');
    const orderProviders = (env.AI_INFERENCE_ORDER || DEFAULT_AI_INFERENCE_ORDER)
      .split(',')
      .map(s => s.trim().toLowerCase())
      .filter(Boolean);
    let orderIndex = 1;
    let skippedCount = 0;
    for (const providerId of orderProviders) {
      const p = PROVIDERS.find(prov => prov.id === providerId);
      if (p) {
        const hasKey = env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`;
        const icon = hasKey ? '✅' : '⏭️';
        const nameStr = `${orderIndex}. ${p.name} (${p.id})`;
        const paddedName = nameStr.padEnd(28);
        if (hasKey) {
          const modelStr = `— model: ${env[p.modelEnv] || p.defaultModel}`;
          const paddedModel = modelStr.padEnd(38);
          console.log(`  ${paddedName}${paddedModel}   ${icon}`);
        } else {
          console.log(`  ${paddedName} ${icon}`);
        }
        skippedCount += hasKey ? 0 : 1;
        orderIndex++;
      }
    }

    if (skippedCount === 4) {
      console.log('');
      console.log('⚠️                                                                                        ⚠️');
      console.log('\tAll providers skipped - no API keys configured');
      console.log('\tIt is recommended to configure at least one provider to use the application.');
      console.log('⚠️                                                                                        ⚠️');
      console.log('');
    }
    console.log('');
    console.log('You can do later:');
    console.log('- Edit AI_INFERENCE_ORDER in .env');
    console.log('- Add or replace API keys in .env');
  } else {
    // Silent mode: ensure at least one key exists
    const hasAnyKey = PROVIDERS.some(p => env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`);
    if (!hasAnyKey) {
      console.log('');
      console.log('Warning: No API keys configured. Run setup.ts without --silent to configure providers.');
    }
  }

  // Step 3: Write .env
  writeEnvFile(ENV_FILE, env);
  if (!isSilent) {
    console.log('');
    console.log('.env was generated successfully ✅');
  }

  if (isSilent) {
    console.log('');
    console.log(`config.json endpoint will serve from .env — order: ${env.AI_INFERENCE_ORDER}`);
  }

  console.log('');
  console.log('╔══════════════════════════════════════════╗');
  console.log('║        Setup complete! 🚀                ║');
  console.log('║        Run `npm start` to launch the app ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log('');
}

main().catch((err: Error) => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});