#!/usr/bin/env node

/**
 * resumessi Setup Script
 * 
 * Cross-platform (Windows, macOS, Linux) Node.js script that:
 * 1. Creates .env from .env.example if missing
 * 2. Prompts for AI_API_KEY and AI_MODEL
 * 3. Writes those values into .env
 * 
 * Usage: node setup.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ROOT = __dirname;
const ENV_EXAMPLE = path.join(ROOT, '.env.example');
const ENV_FILE = path.join(ROOT, '.env');

function ask(question, defaultValue = '') {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });
    return new Promise(resolve => {
        rl.question(question, answer => {
            rl.close();
            resolve(answer.trim() || defaultValue);
        });
    });
}

function parseEnvFile(filePath) {
    const content = fs.readFileSync(filePath, 'utf-8');
    const env = {};
    content.split('\n').forEach(line => {
        line = line.trim();
        if (line.startsWith('#') || !line.includes('=')) return;
        const eqIndex = line.indexOf('=');
        const key = line.substring(0, eqIndex).trim();
        let value = line.substring(eqIndex + 1).trim();
        // Remove surrounding quotes if any
        if ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
        }
        env[key] = value;
    });
    return env;
}

function writeEnvFile(filePath, env) {
    let content = `# resumessi Configuration
# Generated by setup.js — edit this file or re-run: node setup.js

# --- API Configuration ---
AI_API_KEY=${env.AI_API_KEY || 'your_api_key_here'}
AI_MODEL=${env.AI_MODEL || 'gemini-2.5-flash'}
AI_FALLBACK_MODEL=${env.AI_FALLBACK_MODEL || 'llama-3.3-70b-versatile'}
AI_FALLBACK_API_KEY=${env.AI_FALLBACK_API_KEY || 'your_fallback_api_key_here'}

# --- Theme Colors (override as needed) ---
PRIMARY_COLOR=${env.PRIMARY_COLOR || '#0a0a0a'}
SECONDARY_COLOR=${env.SECONDARY_COLOR || '#0a0a0a'}
ACCENT_COLOR=${env.ACCENT_COLOR || '#2563eb'}
TEXT_COLOR=${env.TEXT_COLOR || '#171717'}
TEXT_LIGHT_COLOR=${env.TEXT_LIGHT_COLOR || '#404040'}
BG_BADGE_COLOR=${env.BG_BADGE_COLOR || '#f1f5f9'}
SUCCESS_COLOR=${env.SUCCESS_COLOR || '#0ea5e9'}
`;
    fs.writeFileSync(filePath, content, 'utf-8');
}

async function main() {
    const isSilent = process.argv.includes('--silent');

    if (!isSilent) {
        console.log('');
        console.log('╔══════════════════════════════════════════╗');
        console.log('║        resumessi — Setup Wizard          ║');
        console.log('╚══════════════════════════════════════════╝');
        console.log('');
    }

    // Step 1: Create .env from .env.example if missing
    if (!fs.existsSync(ENV_FILE)) {
        if (fs.existsSync(ENV_EXAMPLE)) {
            fs.copyFileSync(ENV_EXAMPLE, ENV_FILE);
            if (!isSilent) console.log('✅ Created .env from .env.example');
        } else {
            writeEnvFile(ENV_FILE, {});
            if (!isSilent) console.log('✅ Created .env with default values');
        }
    } else {
        if (!isSilent) console.log('✅ .env already exists');
    }

    // Step 2: Read current .env
    const env = parseEnvFile(ENV_FILE);

    if (!isSilent) {
        // Interactive mode — prompt for values
        const currentKey = env.AI_API_KEY && env.AI_API_KEY !== 'your_api_key_here'
            ? env.AI_API_KEY : '';
        const keyHint = currentKey ? `(current: ${currentKey.substring(0, 8)}...)` : '(required)';
        const newKey = await ask(`Enter your AI API Key ${keyHint}: `, currentKey);
        if (newKey) env.AI_API_KEY = newKey;

        const currentModel = env.AI_MODEL || 'gemini-2.5-flash';
        const newModel = await ask(`Enter AI model (default: ${currentModel}): `, currentModel);
        env.AI_MODEL = newModel;
    }

    // Step 3: Write .env
    writeEnvFile(ENV_FILE, env);
    if (!isSilent) console.log('✅ .env updated');

    if (isSilent) {
        console.log(`config.json endpoint will serve from .env — model: ${env.AI_MODEL}`);
    }

    console.log('');
    console.log('╔══════════════════════════════════════════╗');
    console.log('║        Setup complete! 🚀                ║');
    console.log('║        Run `npm start` to launch the app ║');
    console.log('╚══════════════════════════════════════════╝');
    console.log('');
}

main().catch(err => {
    console.error('❌ Error:', err.message);
    process.exit(1);
});