#!/usr/bin/env node

/**
 * resumessi Setup Script
 *
 * WARNING: This script OVERWRITES .env file. Running it will RESET all API keys.
 *          For AI agents: DO NOT run this script as it will cause API keys to be lost or reset.
 *          The setup script is for human users only.
 *
 * Cross-platform (Windows, macOS, Linux) Node.js script that:
 * 1. Creates .env from .env.example if missing
 * 2. Configures AI provider inference order (fallback priority)
 * 3. Prompts for at least one AI provider API key
 * 4. Prompts for SerpAPI key (for Google job scraping)
 * 5. Writes values into .env
 *
 * Usage: tsx setup.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const ROOT = __dirname;
const ENV_EXAMPLE = path.join(ROOT, '.env.example');
const ENV_FILE = path.join(ROOT, '.env');

interface ProviderDef {
	id: string;
	name: string;
	keyEnv: string;
	modelEnv: string;
	defaultModel: string;
}

const PROVIDERS: ProviderDef[] = [
	{
		id: 'cohere',
		name: 'Cohere',
		keyEnv: 'COHERE_API_KEY',
		modelEnv: 'COHERE_MODEL',
		defaultModel: 'command-a-reasoning-08-2025',
	},
	{
		id: 'mistral',
		name: 'Mistral',
		keyEnv: 'MISTRAL_API_KEY',
		modelEnv: 'MISTRAL_MODEL',
		defaultModel: 'codestral-2508',
	},
	{
		id: 'gemini',
		name: 'Gemini',
		keyEnv: 'GEMINI_API_KEY',
		modelEnv: 'GEMINI_MODEL',
		defaultModel: 'gemini-3.6-flash',
	},
	{ id: 'groq', name: 'Groq', keyEnv: 'GROQ_API_KEY', modelEnv: 'GROQ_MODEL', defaultModel: 'openai/gpt-oss-120b' },
];

const PROVIDER_URLS: Record<string, string> = {
	cohere: 'https://dashboard.cohere.com/api-keys',
	mistral: 'https://admin.mistral.ai/organization/api-keys',
	gemini: 'https://aistudio.google.com/api-keys',
	groq: 'https://console.groq.com/keys',
};

const DEFAULT_AI_INFERENCE_ORDER = 'mistral,cohere,gemini,groq';

function ask(question: string, defaultValue: string = ''): Promise<string> {
	const rl = readline.createInterface({
		input: process.stdin,
		output: process.stdout,
	});
	return new Promise(resolve => {
		rl.question(question, answer => {
			rl.close();
			resolve(answer.trim() || defaultValue);
		});
	});
}

function parseEnvFile(filePath: string): Record<string, string | undefined> {
	const content = fs.readFileSync(filePath, 'utf-8');
	const env: Record<string, string | undefined> = {};
	content.split('\n').forEach(line => {
		line = line.trim();
		if (line.startsWith('#') || !line.includes('=')) return;
		const eqIndex = line.indexOf('=');
		const key = line.substring(0, eqIndex).trim();
		let value = line.substring(eqIndex + 1).trim();
		// Remove surrounding quotes if any
		if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
			value = value.slice(1, -1);
		}
		env[key] = value;
	});
	return env;
}

function writeEnvFile(filePath: string, env: Record<string, string | undefined>): void {
	// Preserve all existing keys from current .env (scraper settings, SerpAPI, etc.)
	// while updating AI provider keys and theme colors
	const content = `# resumessi Configuration
# Generated by setup.ts — edit this file or re-run: tsx setup.ts

# --- AI Inference Order ---
# Comma-separated list of providers to try IN ORDER for AI tasks (ATS scoring, resume generation, cover letters).
# The first provider with a valid API key will be used. If it fails, the next is tried.
# Supported providers: cohere, mistral, gemini, groq
AI_INFERENCE_ORDER=${env.AI_INFERENCE_ORDER || DEFAULT_AI_INFERENCE_ORDER}

# --- AI Provider API Keys & Models ---
# Get keys from the provider dashboards. At least ONE key is required for AI features.
COHERE_API_KEY=${env.COHERE_API_KEY || 'your_cohere_key_here'}
COHERE_MODEL=${env.COHERE_MODEL || 'command-a-reasoning-08-2025'}

MISTRAL_API_KEY=${env.MISTRAL_API_KEY || 'your_mistral_key_here'}
MISTRAL_MODEL=${env.MISTRAL_MODEL || 'codestral-2508'}

GEMINI_API_KEY=${env.GEMINI_API_KEY || 'your_gemini_key_here'}
GEMINI_MODEL=${env.GEMINI_MODEL || 'gemini-3.6-flash'}

GROQ_API_KEY=${env.GROQ_API_KEY || 'your_groq_key_here'}
GROQ_MODEL=${env.GROQ_MODEL || 'openai/gpt-oss-120b'}

# --- SerpAPI (Google Job Search) ---
# Get your SerpAPI key at: https://serpapi.com/manage-api-key
# Required for Google job scraping (searches job boards via SerpAPI).
GOOGLE_API_KEY=${env.GOOGLE_API_KEY || ''}

# --- Theme Colors (override as needed) ---
PRIMARY_COLOR=${env.PRIMARY_COLOR || '#0a0a0a'}
SECONDARY_COLOR=${env.SECONDARY_COLOR || '#0a0a0a'}
ACCENT_COLOR=${env.ACCENT_COLOR || '#2563eb'}
TEXT_COLOR=${env.TEXT_COLOR || '#171717'}
TEXT_LIGHT_COLOR=${env.TEXT_LIGHT_COLOR || '#404040'}
BG_BADGE_COLOR=${env.BG_BADGE_COLOR || '#f1f5f9'}
SUCCESS_COLOR=${env.SUCCESS_COLOR || '#0ea5e9'}

`;
	fs.writeFileSync(filePath, content, 'utf-8');
}

async function main(): Promise<void> {
	const isSilent = process.argv.includes('--silent');

	if (!isSilent) {
		console.info('');
		console.info('╔══════════════════════════════════════════╗');
		console.info('║        resumessi — Setup Wizard          ║');
		console.info('╚══════════════════════════════════════════╝');
		console.info('');
	}

	// Step 1: Check if .env exists and warn before overwriting
	if (!fs.existsSync(ENV_FILE)) {
		if (fs.existsSync(ENV_EXAMPLE)) {
			fs.copyFileSync(ENV_EXAMPLE, ENV_FILE);
			if (!isSilent) console.info('Created .env from .env.example ✅');
		} else {
			writeEnvFile(ENV_FILE, {});
			if (!isSilent) console.info('Created .env with default values ✅');
		}
	} else {
		if (!isSilent) {
			console.warn('');
			console.warn(
				'⚠️                                                                                                      ⚠️'
			);
			console.warn('\t.env file already exists.');
			console.warn('\tYour existing keys will be PRESERVED (including SerpAPI, scraper settings, theme colors).');
			console.warn('\tOnly AI provider keys/models and inference order will be updated.');
			console.warn(
				'⚠️                                                                                                      ⚠️'
			);
			console.warn('');
			const confirm = await ask('Type "continue" to proceed: ');
			if (confirm !== 'continue') {
				console.warn('Setup cancelled.');
				process.exit(0);
			}
		}
	}

	// Step 2: Read current .env
	const env = parseEnvFile(ENV_FILE);

	if (!isSilent) {
		console.info('');
		console.info('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
		console.info('STEP 1/2 — AI Provider Configuration');
		console.info('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
		console.info('');
		console.info('The AI_INFERENCE_ORDER defines the FALLBACK PRIORITY for AI tasks.');
		console.info('Providers are tried in order until one succeeds.');
		console.info('');

		const validIds = new Set(PROVIDERS.map(p => p.id));
		const currentOrder = (env.AI_INFERENCE_ORDER || DEFAULT_AI_INFERENCE_ORDER)
			.split(',')
			.map(s => s.trim().toLowerCase())
			.filter(s => validIds.has(s));
		if (currentOrder.length === 0) {
			currentOrder.push(
				...DEFAULT_AI_INFERENCE_ORDER.split(',')
					.map(s => s.trim().toLowerCase())
					.filter(s => validIds.has(s))
			);
		}
		for (let i = 0; i < currentOrder.length; i++) {
			const p = PROVIDERS.find(prov => prov.id === currentOrder[i]);
			if (!p) continue;
			const hasKey = env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`;
			const status = hasKey ? '✅ configured' : '⏭️  no key';
			console.info(`  ${i + 1}. ${p.name} (${p.id}) — ${status}`);
		}

		console.info('');
		console.info('Enter provider IDs in FALLBACK ORDER (comma-separated)');
		console.info(`Current: ${currentOrder.join(',')}`);
		console.info(`Default: ${DEFAULT_AI_INFERENCE_ORDER}`);
		console.info('');

		const selection = await ask('Provider IDs (order matters): ', currentOrder.join(','));
		console.info('');
		const selectedProviders: ProviderDef[] = [];
		const selectedOrder: string[] = [];
		if (selection.trim()) {
			const inputIds = selection
				.split(',')
				.map(s => s.trim().toLowerCase())
				.filter(Boolean);
			for (const providerId of inputIds) {
				const p = PROVIDERS.find(prov => prov.id === providerId);
				if (p) {
					selectedProviders.push(p);
					selectedOrder.push(p.id);
				} else {
					console.warn(`  ⚠️  Unknown provider: ${providerId} (skipped)`);
				}
			}
		}
		if (selectedOrder.length === 0) {
			for (const providerId of currentOrder) {
				const p = PROVIDERS.find(prov => prov.id === providerId);
				if (p) {
					selectedProviders.push(p);
					selectedOrder.push(p.id);
				}
			}
		}
		env.AI_INFERENCE_ORDER = selectedOrder.join(',') || DEFAULT_AI_INFERENCE_ORDER;

		console.info('');
		console.info('Enter API keys for selected providers (leave blank to skip):');
		console.info('');

		for (const p of selectedProviders) {
			const currentKey = env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here` ? env[p.keyEnv] : '';
			const newKey = await ask(`  ${p.name} API Key — ${PROVIDER_URLS[p.id]}: `, currentKey || '');
			if (newKey) {
				env[p.keyEnv] = newKey;
				env[p.modelEnv] = env[p.modelEnv] || p.defaultModel;
			}
		}

		console.info('');
		console.info('Configured AI providers:');
		const orderProviders = (env.AI_INFERENCE_ORDER || DEFAULT_AI_INFERENCE_ORDER)
			.split(',')
			.map(s => s.trim().toLowerCase())
			.filter(Boolean);
		let orderIndex = 1;
		let hasAnyKey = false;
		for (const providerId of orderProviders) {
			const p = PROVIDERS.find(prov => prov.id === providerId);
			if (p) {
				const hasKey = env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`;
				const icon = hasKey ? '✅' : '⏭️';
				const nameStr = `${orderIndex}. ${p.name} (${p.id})`;
				const paddedName = nameStr.padEnd(28);
				if (hasKey) {
					hasAnyKey = true;
					const modelStr = `— model: ${env[p.modelEnv] || p.defaultModel}`;
					const paddedModel = modelStr.padEnd(38);
					console.info(`  ${paddedName}${paddedModel}   ${icon}`);
				} else {
					console.info(`  ${paddedName} ${icon}`);
				}
				orderIndex++;
			}
		}

		if (!hasAnyKey) {
			console.warn('');
			console.warn('⚠️  No AI provider keys configured — AI features will not work.');
			console.warn('   Run setup again or edit .env manually to add keys.');
			console.warn('');
		}

		console.info('');
		console.info('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
		console.info('STEP 2/2 — Job Scraping Configuration');
		console.info('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
		console.info('');
		console.info('Google job scraping uses SerpAPI (not Google directly).');
		console.info('Get a key at: https://serpapi.com/manage-api-key');
		console.info('');

		const currentGoogleKey = env.GOOGLE_API_KEY || '';
		const googleKey = await ask('  SerpAPI Key (GOOGLE_API_KEY): ', currentGoogleKey);
		if (googleKey) {
			env.GOOGLE_API_KEY = googleKey;
		}

		console.info('');
		console.info('LinkedIn scraping uses your browser session (cookies), not an API key.');
		console.info('After setup, run: npm run scraper:auth  (or: tsx scripts/linkedin-auth.ts)');
	} else {
		// Silent mode: ensure at least one key exists
		const hasAnyKey = PROVIDERS.some(p => env[p.keyEnv] && env[p.keyEnv] !== `your_${p.id}_key_here`);
		if (!hasAnyKey) {
			console.warn('');
			console.warn('Warning: No API keys configured. Run setup.ts without --silent to configure providers.');
		}
	}

	// Step 3: Write .env
	writeEnvFile(ENV_FILE, env);
	if (!isSilent) {
		console.info('');
		console.info('.env was generated successfully ✅');
		console.info('');
		console.info('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
		console.info('NEXT STEPS:');
		console.info('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
		console.info('1. LinkedIn auth (for LinkedIn scraping):');
		console.info('   npm run scraper:auth');
		console.info('');
		console.info('2. Start the app:');
		console.info('   npm start');
		console.info('');
	}

	if (isSilent) {
		console.info('');
		console.info(`config.json endpoint will serve from .env — order: ${env.AI_INFERENCE_ORDER}`);
	}

	console.info('');
	console.info('╔══════════════════════════════════════════╗');
	console.info('║        Setup complete! 🚀                ║');
	console.info('║        Run `npm start` to launch the app ║');
	console.info('╚══════════════════════════════════════════╝');
	console.info('');
}

main().catch((err: Error) => {
	console.error('❌ Error:', err.message);
	process.exit(1);
});
