#!/usr/bin/env sh
set -e

echo "Running pre-commit validations..."

# Ensure 6gb of memory allocation for the pre-commit process
export NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=6144}"

npx lint-staged --concurrent false
npm run validate -- --skip-evals
npm run typecheck
npm run lint
npm run html:validate
npm run css:validate
npm run build

echo "All validations passed ✅"