#!/usr/bin/env sh
set -e

echo "Running pre-commit validations..."

npm run typecheck
npm run lint
npm run test:unit
npm run html:validate
npm run css:validate
npm run build

echo "All validations passed ✅"